export type FlagMeta = { code: string; name: string; region: "EU"|"AF"|"AS"|"AM"|"OC" };
/** Stub pool (to be replaced with full list in implementation) */
export const FLAG_POOL_STUB: FlagMeta[] = [
  // Europe (EU)
  { code: "AL", name: "Albania", region: "EU" },
  { code: "AT", name: "Austria", region: "EU" },
  { code: "BE", name: "Belgium", region: "EU" },
  { code: "BA", name: "Bosnia and Herzegovina", region: "EU" },
  { code: "BG", name: "Bulgaria", region: "EU" },
  { code: "HR", name: "Croatia", region: "EU" },
  { code: "CY", name: "Cyprus", region: "EU" },
  { code: "CZ", name: "Czechia", region: "EU" },
  { code: "DK", name: "Denmark", region: "EU" },
  { code: "EE", name: "Estonia", region: "EU" },
  { code: "FI", name: "Finland", region: "EU" },
  { code: "FR", name: "France", region: "EU" },
  { code: "DE", name: "Germany", region: "EU" },
  { code: "GR", name: "Greece", region: "EU" },
  { code: "HU", name: "Hungary", region: "EU" },
  { code: "IS", name: "Iceland", region: "EU" },
  { code: "IE", name: "Ireland", region: "EU" },
  { code: "IT", name: "Italy", region: "EU" },
  { code: "LV", name: "Latvia", region: "EU" },
  { code: "LI", name: "Liechtenstein", region: "EU" },
  { code: "LT", name: "Lithuania", region: "EU" },
  { code: "LU", name: "Luxembourg", region: "EU" },
  { code: "MT", name: "Malta", region: "EU" },
  { code: "MD", name: "Moldova", region: "EU" },
  { code: "ME", name: "Montenegro", region: "EU" },
  { code: "NL", name: "Netherlands", region: "EU" },
  { code: "MK", name: "North Macedonia", region: "EU" },
  { code: "NO", name: "Norway", region: "EU" },
  { code: "PL", name: "Poland", region: "EU" },
  { code: "PT", name: "Portugal", region: "EU" },
  { code: "RO", name: "Romania", region: "EU" },
  { code: "RS", name: "Serbia", region: "EU" },
  { code: "SK", name: "Slovakia", region: "EU" },
  { code: "SI", name: "Slovenia", region: "EU" },
  { code: "ES", name: "Spain", region: "EU" },
  { code: "SE", name: "Sweden", region: "EU" },
  { code: "CH", name: "Switzerland", region: "EU" },
  { code: "UA", name: "Ukraine", region: "EU" },
  { code: "GB", name: "United Kingdom", region: "EU" },
  // Africa (AF)
  { code: "DZ", name: "Algeria", region: "AF" },
  { code: "AO", name: "Angola", region: "AF" },
  { code: "BJ", name: "Benin", region: "AF" },
  { code: "BW", name: "Botswana", region: "AF" },
  { code: "CM", name: "Cameroon", region: "AF" },
  { code: "CI", name: "Côte d’Ivoire", region: "AF" },
  { code: "EG", name: "Egypt", region: "AF" },
  { code: "ET", name: "Ethiopia", region: "AF" },
  { code: "GH", name: "Ghana", region: "AF" },
  { code: "KE", name: "Kenya", region: "AF" },
  { code: "MA", name: "Morocco", region: "AF" },
  { code: "MZ", name: "Mozambique", region: "AF" },
  { code: "NG", name: "Nigeria", region: "AF" },
  { code: "SN", name: "Senegal", region: "AF" },
  { code: "TZ", name: "Tanzania", region: "AF" },
  { code: "TN", name: "Tunisia", region: "AF" },
  { code: "UG", name: "Uganda", region: "AF" },
  { code: "ZA", name: "South Africa", region: "AF" },
  { code: "ZW", name: "Zimbabwe", region: "AF" },
  // Asia (AS)
  { code: "AE", name: "United Arab Emirates", region: "AS" },
  { code: "AM", name: "Armenia", region: "AS" },
  { code: "BD", name: "Bangladesh", region: "AS" },
  { code: "BN", name: "Brunei", region: "AS" },
  { code: "CN", name: "China", region: "AS" },
  { code: "GE", name: "Georgia", region: "AS" },
  { code: "IN", name: "India", region: "AS" },
  { code: "ID", name: "Indonesia", region: "AS" },
  { code: "IL", name: "Israel", region: "AS" },
  { code: "IR", name: "Iran", region: "AS" },
  { code: "IQ", name: "Iraq", region: "AS" },
  { code: "JP", name: "Japan", region: "AS" },
  { code: "JO", name: "Jordan", region: "AS" },
  { code: "KZ", name: "Kazakhstan", region: "AS" },
  { code: "KR", name: "Korea, South", region: "AS" },
  { code: "KW", name: "Kuwait", region: "AS" },
  { code: "LB", name: "Lebanon", region: "AS" },
  { code: "MY", name: "Malaysia", region: "AS" },
  { code: "MN", name: "Mongolia", region: "AS" },
  { code: "NP", name: "Nepal", region: "AS" },
  { code: "PK", name: "Pakistan", region: "AS" },
  { code: "PH", name: "Philippines", region: "AS" },
  { code: "QA", name: "Qatar", region: "AS" },
  { code: "SA", name: "Saudi Arabia", region: "AS" },
  { code: "SG", name: "Singapore", region: "AS" },
  { code: "LK", name: "Sri Lanka", region: "AS" },
  { code: "SY", name: "Syria", region: "AS" },
  { code: "TH", name: "Thailand", region: "AS" },
  { code: "TR", name: "Türkiye", region: "AS" },
  { code: "TW", name: "Taiwan", region: "AS" },
  { code: "VN", name: "Vietnam", region: "AS" },
  // Americas (AM)
  { code: "AR", name: "Argentina", region: "AM" },
  { code: "BS", name: "Bahamas", region: "AM" },
  { code: "BO", name: "Bolivia", region: "AM" },
  { code: "BR", name: "Brazil", region: "AM" },
  { code: "CA", name: "Canada", region: "AM" },
  { code: "CL", name: "Chile", region: "AM" },
  { code: "CO", name: "Colombia", region: "AM" },
  { code: "CR", name: "Costa Rica", region: "AM" },
  { code: "CU", name: "Cuba", region: "AM" },
  { code: "DO", name: "Dominican Republic", region: "AM" },
  { code: "EC", name: "Ecuador", region: "AM" },
  { code: "SV", name: "El Salvador", region: "AM" },
  { code: "GT", name: "Guatemala", region: "AM" },
  { code: "HN", name: "Honduras", region: "AM" },
  { code: "JM", name: "Jamaica", region: "AM" },
  { code: "MX", name: "Mexico", region: "AM" },
  { code: "NI", name: "Nicaragua", region: "AM" },
  { code: "PA", name: "Panama", region: "AM" },
  { code: "PY", name: "Paraguay", region: "AM" },
  { code: "PE", name: "Peru", region: "AM" },
  { code: "UY", name: "Uruguay", region: "AM" },
  { code: "US", name: "United States", region: "AM" },
  { code: "VE", name: "Venezuela", region: "AM" },
  // Oceania (OC)
  { code: "AU", name: "Australia", region: "OC" },
  { code: "FJ", name: "Fiji", region: "OC" },
  { code: "PG", name: "Papua New Guinea", region: "OC" },
  { code: "NZ", name: "New Zealand", region: "OC" },
  { code: "SB", name: "Solomon Islands", region: "OC" },
  { code: "TO", name: "Tonga", region: "OC" },
  { code: "VU", name: "Vanuatu", region: "OC" },
  { code: "WS", name: "Samoa", region: "OC" },
];

export const REGIONS = [
  { id: "ALL", label: "World" },
  { id: "EU", label: "Europe" },
  { id: "AF", label: "Africa" },
  { id: "AS", label: "Asia" },
  { id: "AM", label: "Americas" },
  { id: "OC", label: "Oceania" },
];
