services:
  api:
    build: { context: ../.., dockerfile: infra/docker/Dockerfile.api }
    env_file: ../../.env
    environment: [ "NODE_ENV=development" ]
    ports: [ "${PORT_API:-4000}:4000" ]
    command: pnpm -C apps/api dev
  web:
    build: { context: ../.., dockerfile: infra/docker/Dockerfile.web }
    env_file: ../../.env
    environment:
      - NODE_ENV=development
      - BASE_PATH=${BASE_PATH:-/}
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_API_URL=http://localhost:${PORT_API:-4000}/v1/ping
    ports: [ "${PORT_WEB:-3000}:3000" ]
    command: pnpm -C apps/web dev
    depends_on: [ "api" ]
