version: "3.9"
services:
  api:
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile.api
    env_file: ../../.env
    ports:
      - "4000:4000"
    command: ["node", "dist/index.js"]

  web:
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile.web
    env_file: ../../.env
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000
      - BASE_PATH=${BASE_PATH:-/}
    command: ["npx", "next", "start", "-p", "3000"]
